
[item_pipe]

	[item_pipe.speed]
		#The speed at which items are transferred
		#A value of 1 means every tick
		#Range: > 1
		no_upgrade = 20
		#The speed at which items are transferred
		#A value of 1 means every tick
		#Range: > 1
		basic = 10
		#The speed at which items are transferred
		#A value of 1 means every tick
		#Range: > 1
		improved = 5
		#The speed at which items are transferred
		#A value of 1 means every tick
		#Range: > 1
		advanced = 1
		#The speed at which items are transferred
		#A value of 1 means every tick
		#Range: > 1
		ultimate = 1

	[item_pipe.amount]
		#The amount of items transferred
		#Range: > 1
		no_upgrade = 16
		#The amount of items transferred
		#Range: > 1
		basic = 16
		#The amount of items transferred
		#Range: > 1
		improved = 32
		#The amount of items transferred
		#Range: > 1
		advanced = 64
		#The amount of items transferred
		#Range: > 1
		ultimate = 128

[fluid_pipe]

	[fluid_pipe.amount]
		#The amount of mB transferred each tick
		#Range: > 1
		no_upgrade = 1000
		#The amount of mB transferred each tick
		#Range: > 1
		basic = 5000
		#The amount of mB transferred each tick
		#Range: > 1
		improved = 20000
		#The amount of mB transferred each tick
		#Range: > 1
		advanced = 100000
		#The amount of mB transferred each tick
		#Range: > 1
		ultimate = 50000000

[energy_pipe]

	[energy_pipe.amount]
		#The amount of FE transferred each tick
		#Range: > 1
		no_upgrade = 1024
		#The amount of FE transferred each tick
		#Range: > 1
		basic = 8192
		#The amount of FE transferred each tick
		#Range: > 1
		improved = 32768
		#The amount of FE transferred each tick
		#Range: > 1
		advanced = 131072
		#The amount of FE transferred each tick
		#Range: > 1
		ultimate = 1310720

[gas_pipe]

	[gas_pipe.amount]
		#The amount of mB transferred each tick
		#Only available if Mekanism is installed
		#Range: > 1
		no_upgrade = 200
		#The amount of mB transferred each tick
		#Only available if Mekanism is installed
		#Range: > 1
		basic = 400
		#The amount of mB transferred each tick
		#Only available if Mekanism is installed
		#Range: > 1
		improved = 2000
		#The amount of mB transferred each tick
		#Only available if Mekanism is installed
		#Range: > 1
		advanced = 8000
		#The amount of mB transferred each tick
		#Only available if Mekanism is installed
		#Range: > 1
		ultimate = 40000

