
["Carved Faction"]
	#Carved Obligation
	"铜刻佣兵团是否主动攻击僵尸类[Zombies]、袭击类生物[Raiders]以外[other than]的敌对生物" = true
	#Carved Active Attack Creeper
	"铜刻佣兵团主动攻击苦力怕[Creeper]" = false
	#Carved Gonna Active Attack List
	"铜刻佣兵团 会主动攻击生物" = ["minecraft:zombie"]
	#Carved Never Gonna Active Attack List
	"铜刻佣兵团 不会主动攻击生物" = ["minecraft:villager", "minecraft:iron_golem", "minecraft:wandering_trader"]
	#Carved Hound Retire
	"驯服后的铜刻猎犬不再主动协助村民、铜刻生物、信任玩家" = true

["Tame Mob"]
	#Tame Mob Hurt By Owner Has Reduce
	"驯服生物是否对主人对自身造成的伤害拥有减伤" = true
	#Tame Mob Attack Creeper And Ghast
	"模组添加的驯服生物是否攻击苦力怕和恶魂" = false

[Other]
	#Wicked Ridicule Night BossBar
	"Wicked Ridicule Night BossBar" = true

[Attributes]

	[Attributes.Boss]

		[Attributes.Boss."Sediment Lord"]
			#[Boss] Max Health : 170.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Sediment Lord Max Health" = 170.0
			#[Boss] Melee Damage : 6.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Sediment Lord Melee Damage" = 6.0
			#[Boss] Armor : 3.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Sediment Lord Armor" = 3.0
			#[Boss] Movement Speed : 0.20
			#Range: 0.0 ~ 1.7976931348623157E308
			"Sediment Lord Movement Speed" = 0.2
			#[Boss] Attack Knockback : 0.4
			#Range: 0.0 ~ 1.7976931348623157E308
			"Sediment Lord Attack Knockback" = 0.4
			#[Boss] Knockback Resistance : 0.5
			#Range: 0.0 ~ 1.7976931348623157E308
			"Sediment Lord Knockback Resistance" = 0.5
			#[Boss] Lead Cooldown : 30.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Sediment Lord Lead Cooldown" = 30.0
			#[Boss] Drop Equipment Chance : 0.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Sediment Lord Drop Equipment Chance" = 0.0

		[Attributes.Boss.Corrosiver]
			#[Boss] Max Health : 185.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Corrosiver Max Health" = 185.0
			#[Boss] Melee Damage : 12.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Corrosiver Melee Damage" = 12.0
			#[Boss] Armor : 5.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Corrosiver Armor" = 5.0
			#[Boss] Movement Speed : 0.32
			#Range: 0.0 ~ 1.7976931348623157E308
			"Corrosiver Movement Speed" = 0.32
			#[Boss] Attack Knockback : 0.6
			#Range: 0.0 ~ 1.7976931348623157E308
			"Corrosiver Attack Knockback" = 0.6
			#[Boss] Knockback Resistance : 1.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Corrosiver Knockback Resistance" = 1.0
			#[Boss] Hurt Cooldown : 2.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Corrosiver Hurt Cooldown" = 2.0
			#[Boss] Break Hurt Cooldown Multiple : 3
			#Range: 0.0 ~ 1.7976931348623157E308
			"Corrosiver Break Hurt Cooldown Multiple" = 3.0
			#[Boss] Breath Normal Level : 3
			#Range: > 0
			"Corrosiver Breath Normal Level" = 3
			#[Boss] Breath Cooldown : 12.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Corrosiver Breath Cooldown" = 12.0
			#[Boss] Breath Count : 3
			#Range: > 0
			"Corrosiver Breath Count" = 3
			#[Boss] Breath Count Wind : 5
			#Range: > 0
			"Corrosiver Breath Count Wind" = 5

		[Attributes.Boss."Purple Sand Hag"]
			#[Boss] Max Health : 165.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Purple Sand Hag Max Health" = 165.0
			#[Boss] Melee Damage : 13.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Purple Sand Hag Melee Damage" = 13.0
			#[Boss] Armor : 15.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Purple Sand Hag Armor" = 15.0
			#[Boss] Movement Speed : 0.4
			#Range: 0.0 ~ 1.7976931348623157E308
			"Purple Sand Hag Movement Speed" = 0.4
			#[Boss] Attack Knockback : 0.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Purple Sand Hag Attack Knockback" = 0.0
			#[Boss] Knockback Resistance : 0.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Purple Sand Hag Knockback Resistance" = 0.0
			#[Boss] Main Spell Cooldown : 6.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Purple Sand Hag Main Spell Cooldown" = 6.0
			#[Boss] Other Spell Cooldown : 6.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Purple Sand Hag Other Spell Cooldown" = 6.0
			#[Boss] Spell Normal Level : 3
			#Range: > 0
			"Purple Sand Hag Spell Normal Level" = 3

		[Attributes.Boss."Gemstone Malignasaur"]
			#[Boss] Max Health : 348.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Gemstone Malignasaur Max Health" = 348.0
			#[Boss] Melee Damage : 14.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Gemstone Malignasaur Melee Damage" = 14.0
			#[Boss] Armor : 4.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Gemstone Malignasaur Armor" = 4.0
			#[Boss] Armor Gemstone Armor : 20.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Gemstone Malignasaur Armor Gemstone Armor" = 20.0
			#[Boss] Movement Speed : 1.3
			#Range: 0.0 ~ 1.7976931348623157E308
			"Gemstone Malignasaur Movement Speed" = 1.3
			#[Boss] Movement Speed Gemstone Armor : 1.4
			#Range: 0.0 ~ 1.7976931348623157E308
			"Gemstone Malignasaur Movement Speed Gemstone Armor" = 1.4
			#[Boss] Attack Knockback : 2.8
			#Range: 0.0 ~ 1.7976931348623157E308
			"Gemstone Malignasaur Attack Knockback" = 2.8
			#[Boss] Knockback Resistance : 1.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Gemstone Malignasaur Knockback Resistance" = 1.0
			#[Boss] Hurt Cooldown : 1.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Gemstone Malignasaur Hurt Cooldown" = 1.0
			#[Boss] Break Hurt Cooldown Multiple : 3
			#Range: 0.0 ~ 1.7976931348623157E308
			"Gemstone Malignasaur Break Hurt Cooldown Multiple" = 3.0
			#[Boss] Jump Attack Level : 3
			#Range: > 0
			"Gemstone Malignasaur Jump Attack Level" = 3
			#[Boss] Jump Attack Cooldown : 18
			#Range: 0.0 ~ 1.7976931348623157E308
			"Gemstone Malignasaur Jump Attack Cooldown" = 18.0
			#[Boss] Breath Normal Level : 3
			#Range: > 0
			"Gemstone Malignasaur Breath Normal Level" = 3
			#[Boss] Breath Cooldown : 30.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Gemstone Malignasaur Breath Cooldown" = 30.0
			#[Boss] Control Normal Level : 3
			#Range: > 0
			"Gemstone Malignasaur Control Normal Level" = 3
			#[Boss] Control Cooldown : 60.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Gemstone Malignasaur Control Cooldown" = 60.0
			#[Boss] Deter Cooldown : 120.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Gemstone Malignasaur Deter Cooldown" = 120.0
			#[Boss] Damage Suffered Value : 30.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Gemstone Malignasaur Damage Suffered Value" = 30.0
			#[Boss] Break Damage Suffered Value : 105.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Gemstone Malignasaur Break Damage Suffered Value" = 105.0
			#[Boss] Break Block Cooldown : 1.5
			#Range: 0.0 ~ 1.7976931348623157E308
			"Gemstone Malignasaur Break Block Cooldown" = 1.5

		[Attributes.Boss."Bright Land Beast"]
			#[Boss] Max Health : 650.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Bright Land Beast Max Health" = 650.0
			#[Boss] Melee Damage : 40.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Bright Land Beast Melee Damage" = 40.0
			#[Boss] Armor : 4.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Bright Land Beast Armor" = 4.0
			#[Boss] Movement Speed : 0.28
			#Range: 0.0 ~ 1.7976931348623157E308
			"Bright Land Beast Movement Speed" = 0.28
			#[Boss] Attack Knockback : 4.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Bright Land Beast Attack Knockback" = 4.0
			#[Boss] Knockback Resistance : 1.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Bright Land Beast Knockback Resistance" = 1.0
			#[Boss] Hurt Cooldown : 1.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Bright Land Beast Hurt Cooldown" = 1.0
			#[Boss] Break Breath Cooldown Multiple : 3
			#Range: 0.0 ~ 1.7976931348623157E308
			"Bright Land Beast Break Hurt Cooldown Multiple" = 3.0
			#[Boss] Melee Attack Cooldown : 3.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Bright Land Beast Melee Attack Cooldown" = 3.0
			#[Boss] Trample Cooldown : 2.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Bright Land Beast Trample Cooldown" = 2.0
			#[Boss] Quake Cooldown : 20.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Bright Land Beast Quake Cooldown" = 20.0
			#[Boss] Break Block Cooldown : 1
			#Range: 0.0 ~ 1.7976931348623157E308
			"Bright Land Beast Break Block Cooldown" = 1.0

		[Attributes.Boss."Second Rounder Golem"]
			#[Boss] Max Health : 436.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Second Rounder Golem Max Health" = 436.0
			#[Boss] Melee Damage : 36.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Second Rounder Golem Melee Damage" = 36.0
			#[Boss] Melee Damage Use Sword : 48.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Second Rounder Golem Melee Damage Use Sword" = 48.0
			#[Boss] Armor : 20.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Second Rounder Golem Armor" = 20.0
			#[Boss] Movement Speed : 0.30
			#Range: 0.0 ~ 1.7976931348623157E308
			"Second Rounder Golem Movement Speed" = 0.28
			#[Boss] Movement Speed Use Sword : 0.30
			#Range: 0.0 ~ 1.7976931348623157E308
			"Second Rounder Golem Movement Speed Use Sword" = 0.28
			#[Boss] Attack Knockback : 3.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Second Rounder Golem Attack Knockback" = 3.0
			#[Boss] Knockback Resistance : 1.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Second Rounder Golem Knockback Resistance" = 1.0
			#[Boss] Armor Use Sword : 26.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Second Rounder Golem Armor Use Sword" = 26.0
			#[Boss] Breath Normal Level : 12
			#Range: > 0
			"Second Rounder Golem Breath Normal Level" = 12
			#[Boss] Breath Cooldown : 24.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Second Rounder Golem Breath Cool down" = 24.0
			#[Boss] Breath Count : 6
			#Range: > 0
			"Second Rounder Golem Breath Count" = 6
			#[Boss] Intense Bombing Normal Level : 3
			#Range: > 0
			"Second Rounder Golem Intense Bombing Normal Level" = 3
			#[Boss] Intense Bombing Cooldown : 60.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Second Rounder Golem Intense Bombing Cooldown" = 60.0
			#[Boss] Fire Absorption Percentage : 100.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Second Rounder Golem Fire Absorption Percentage" = 100.0
			#[Boss] Not Attacked Start Heal Cooldown : 20.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Second Rounder Golem Not Attacked Start Heal Cooldown" = 20.0
			#[Boss] Normal Meror Toughness Non Magical : 4.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Second Rounder Golem Normal Meror Toughness Non Magical" = 4.0
			#[Boss] Normal Meror Toughness Magical : 6.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"Second Rounder Golem Normal Meror Toughness Magical" = 6.0
			#[Boss] Break Block Cooldown : 2
			#Range: 0.0 ~ 1.7976931348623157E308
			"Second Rounder Golem Break Block Cooldown" = 2.0

